language: python
python:
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  -  pip install -r "Requirements.txt" 
script: python Assignment#2.py 

after_success:
  - codecov # submit coverage
